esphome:
  name: tmd-kaisai-hp
  friendly_name: "TMDesign Heat Pump"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
  level: INFO

api:
  encryption:
    key: "vyYmiYN9t1myYTjkeQPXAIBYZItszGJSJsFuTDXp5RE="

ota:
  - platform: esphome
    password: "e66731cdf458108107b16c5cf33e1667"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "TMD-Kaisai-HP Fallback"
    password: "09NtoZOFA5ev"

captive_portal:

uart:
  id: tmd_uart_modbus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600
  stop_bits: 1

modbus:
  id: tmd_modbus

modbus_controller:
  - id: tmd_hp
    modbus_id: tmd_modbus
    address: 1
    update_interval: 10s

sensor:
  - platform: modbus_controller
    modbus_controller_id: tmd_hp
    name: "TMD HP Supply Temperature"
    address: 100
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "°C"
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: tmd_hp
    name: "TMD HP Outdoor Temperature"
    address: 101
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "°C"
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: tmd_hp
    name: "TMD HP COP"
    address: 120
    register_type: holding
    value_type: U_WORD
    filters:
      - multiply: 0.1

binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: tmd_hp
    name: "TMD HP Compressor Running"
    address: 200
    register_type: holding
    bitmask: 0x0001

  - platform: modbus_controller
    modbus_controller_id: tmd_hp
    name: "TMD HP Defrost Active"
    address: 200
    register_type: holding
    bitmask: 0x0002
