esphome:
  name: tmdesign-oczyszczalnia
  friendly_name: tmdesign-oczyszczalnia
  on_boot:
    priority: 600
    then:
      - lambda: |-
          id(tmd_master).publish_state(true);

          id(tmd_state) = 0;
          id(tmd_timer) = 0;

          id(tmd_r1).turn_on();
          id(tmd_r2).turn_on();
          id(tmd_r3).turn_off();
          id(tmd_r4).turn_off();

packages:
  - !include common/infrastructure.yaml
  - !include packages/oczyszczalnia/io.yaml
  - !include packages/oczyszczalnia/display.yaml
  - !include packages/oczyszczalnia/logic.yaml

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

i2c:
  sda: GPIO8
  scl: GPIO9
  scan: true
