switch:
  - platform: gpio
    pin: GPIO4
    name: "TMD R1 Sprężarka"
    id: tmd_r1
    restore_mode: ALWAYS_OFF

  - platform: gpio
    pin: GPIO5
    name: "TMD R2 Napowietrzanie"
    id: tmd_r2
    restore_mode: ALWAYS_OFF

  - platform: gpio
    pin: GPIO6
    name: "TMD R3 Mamut1"
    id: tmd_r3
    restore_mode: ALWAYS_OFF

  - platform: gpio
    pin: GPIO7
    name: "TMD R4 Mamut2"
    id: tmd_r4
    restore_mode: ALWAYS_OFF

  - platform: template
    name: "TMD MASTER ENABLE"
    id: tmd_master
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    on_turn_on:
      - lambda: |-
          ESP_LOGI("TMD", "MASTER ON – restart cyklu");
          id(tmd_state) = 0;
          id(tmd_timer) = 0;
          id(tmd_force_refresh) = true;

    on_turn_off:
      - lambda: |-
          ESP_LOGI("TMD", "MASTER OFF – zatrzymanie systemu");
          id(tmd_timer) = 0;

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: true

    name: "TMD Przycisk Panel"
    id: tmd_panel_button

    filters:
      - delayed_on: 20ms
      - delayed_off: 20ms

    on_press:
      then:
        - lambda: |-

            // 1️⃣ Jeśli ekran wygaszony → tylko go włącz
            if (id(tmd_screen_timer) <= 0) {
              id(tmd_screen_timer) = 60;
              return;
            }

            // 2️⃣ Jeśli SAFE aktywny → reset alarmu
            if (id(tmd_safe_mode)) {

              id(tmd_alarm_latched) = false;
              id(tmd_safe_mode) = false;
              id(tmd_alarm_active_code) = 0;
              id(tmd_alarm_active_timestamp) = 0;
              id(tmd_alarm_count) = 0;

              id(tmd_state) = 0;
              id(tmd_timer) = 0;

              id(tmd_screen_timer) = 60;
              return;
            }

            // 3️⃣ Jeśli brak SAFE → przełącz MASTER
            bool master = id(tmd_master).state;
            id(tmd_master).publish_state(!master);

            id(tmd_screen_timer) = 60;

number:
  - platform: template
    name: "TMD Czas Aeracja"
    id: tmd_time_aeracja
    optimistic: true
    min_value: 30
    max_value: 180
    step: 1
    initial_value: 45

  - platform: template
    name: "TMD Czas Pauza"
    id: tmd_time_pauza
    optimistic: true
    min_value: 2
    max_value: 10
    step: 0.1
    initial_value: 5

  - platform: template
    name: "TMD Czas Mamut1"
    id: tmd_time_m1
    optimistic: true
    min_value: 2
    max_value: 15
    step: 0.1
    initial_value: 10

  - platform: template
    name: "TMD Czas Aeracja Stabilizacja"
    id: tmd_time_aer2
    optimistic: true
    min_value: 2
    max_value: 10
    step: 0.1
    initial_value: 5

  - platform: template
    name: "TMD Czas Mamut2"
    id: tmd_time_m2
    optimistic: true
    min_value: 1
    max_value: 5
    step: 0.1
    initial_value: 3

sensor:
  - platform: template
    id: tmd_czas_w_stanie
    name: "TMD Czas w stanie [min]"
    unit_of_measurement: "min"
    accuracy_decimals: 2
    lambda: |-
      return id(tmd_timer) / 60.0;
    update_interval: 2s

button:
  - platform: template
    id: tmd_reset_alarm_btn
    name: "TMD RESET ALARM"
    on_press:
      then:
        - lambda: |-
            id(tmd_alarm_latched) = false;
            id(tmd_safe_mode) = false;
            id(tmd_alarm_active_code) = 0;
            id(tmd_alarm_active_timestamp) = 0;
            id(tmd_alarm_count) = 0;

        - lambda: |-
            id(tmd_state) = 0;
            id(tmd_timer) = 0;

text_sensor:
  - platform: template
    id: tmd_aktualny_stan
    name: "TMD Aktualny Stan"
    lambda: |-
      switch(id(tmd_state)) {
        case 0: return {"AERACJA"};
        case 1: return {"OSAD"};
        case 2: return {"MAMUT1"};
        case 3: return {"AERACJA OSAD"};
        case 4: return {"AERACJA + MAMUT2"};
        default: return {"NIEZNANY"};
      }
    update_interval: 2s
