esphome:
  name: kaisai
  friendly_name: kaisai

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "NXh1VmuqV/x11AIvGvpKdn0eM7wjJSFa2KoBgVQYlLM="
  address: 192.168.0.101

ota:
  - platform: esphome
    password: "bd50b3d8e8f853ed5b8a3ec131756427"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Musial2.5"
    password: "Zal30Tes18Got13"

captive_portal: