esphome:
  name: tmd-kaisai-hp
  friendly_name: "TMDesign Heat Pump"
  comment: "TMDesign (TMD) – Kaisai / Modbus – RO skeleton"

esp32:
  board: esp32dev

logger:
  level: INFO

api:
  reboot_timeout: 0s

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

uart:
  id: tmd_uart_modbus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600
  stop_bits: 1

modbus:
  id: tmd_modbus

modbus_controller:
  - id: tmd_hp
    modbus_id: tmd_modbus
    address: 1
    setup_priority: -10
    update_interval: 10s

packages:
  sensors: !include tmd_sensors_ro.yaml
  binary: !include tmd_binary_ro.yaml
